'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmSearchUsers

    '''<summary>
    '''dgvSearch_UserData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvSearch_UserData As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''DSUsersMobile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSUsersMobile As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''DSUsersWeb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSUsersWeb As Global.System.Web.UI.WebControls.SqlDataSource
End Class
