'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmCreateUser

    '''<summary>
    '''RegisterUserWithRoles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegisterUserWithRoles As Global.System.Web.UI.WebControls.CreateUserWizard

    '''<summary>
    '''CreateUserWizardStep2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateUserWizardStep2 As Global.System.Web.UI.WebControls.CreateUserWizardStep

    '''<summary>
    '''SpecifyRolesStep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SpecifyRolesStep As Global.System.Web.UI.WebControls.WizardStep

    '''<summary>
    '''Rolelist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Rolelist As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''CompleteWizardStep2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompleteWizardStep2 As Global.System.Web.UI.WebControls.CompleteWizardStep
End Class
